Update Turtle to 0.1.5
elementary/appcenter-reviews pull request #103
Opened 2021-08-26 16:03 UTC by amka

- Repository: [tenderowl/turtle](https://github.com/tenderowl/turtle)
- Submitted by: @amka
- Tag: https://github.com/TenderOwl/Turtle/releases/tag/0.1.5
- Diff: https://github.com/TenderOwl/Turtle/compare/0.1.1...0.1.5

## Review Checklist

- [x] App opens
- [x] Does what it says
- [x] Matches description in AppData
- [x] Matches screenshot
- [x] AppData custom colors are contrasty
- [x] Name is unique and non-confusing
- [x] Uses elementary Flatpak runtime
- [x] Sandbox permissions are reasonable
- [x] https://github.com/TenderOwl/Turtle/issues/12

2021-08-28 09:39 UTC, amka commented
[0.1.5](TenderOwl/Turtle/releases/tag/0.1.5) pushed with updated release tag and keywords.
Hash: `c2642da47a7cb40c6b61f3d8021a102be2dd0f9d`

2021-08-31 21:40 UTC, cassidyjames approved these changes

2021-08-31 21:42 UTC, cassidyjames requested changes
@amka it looks like you didn't give permission to repo editors to edit your submission. Can you please correct the version and commit hash in the PR?

2021-08-31 22:10 UTC, amka commented
Oh, that is what I gonna set correct next time :)

2021-09-01 20:27 UTC, cassidyjames approved these changes

2021-09-01 20:27 UTC, merged