com.github.ckruse.ColorMate 1.0.4
elementary/appcenter-reviews pull request #141
Opened 2021-09-21 19:06 UTC by ckruse

2021-09-21 22:18 UTC, danrabbit approved these changes
Nice new icon!

2021-09-21 22:19 UTC, danrabbit requested changes
Ah, it looks like unfortunately because of the formatting in your release notes the build isn't succeeding

2021-09-22 04:38 UTC, ckruse commented
Sorry. 1.0.5 fixes this.

`appstream-util` validation is pretty strict. Never thought a link wouldn't be allowed.

2021-09-23 13:22 UTC, davidmhewitt approved these changes

2021-09-23 18:28 UTC, danrabbit approved these changes

2021-09-23 18:31 UTC, merged