com.github.childishgiant.mixer 0.1.4
elementary/appcenter-reviews pull request #195
Opened 2021-11-10 21:25 UTC by ChildishGiant

Let's try again! I've dropped the stripe key (I'm in no rush to get that sorted), updated changelogs and merged Danielle's change to appdata.
https://github.com/ChildishGiant/mixer/releases/tag/0.1.4

2021-11-10 23:35 UTC, danrabbit approved these changes

2021-11-10 23:35 UTC, danrabbit requested changes
Ah, I just noticed your timestamp in AppData is `2021-08-30`. I imagine you probably want to update that to `2021-11-10` :)

2021-11-10 23:42 UTC, ChildishGiant commented
Ah so the release was made them, I just forgot to push it all until now as whenever I've been working on mixer it's been working on the rewrite

2021-11-11 01:36 UTC, danrabbit commented
@ChildishGiant alright if you don't want to update it no big deal, just know that the homepage uses this tag to choose recently updated apps and it might be confusing for users to get an update that says it's 3 months old

You don't have to worry about the Launchable tag. The checklist is for reviewers not submitters. It's just a reminder in case somebody has a launchable tag in their appdata to make sure it matches since we've had problems with it in the past. But it's not required

2021-11-11 15:18 UTC, ChildishGiant commented
I think I won't bother if that's all good, it's not a major update; just some fixes and l18n.

2021-11-11 18:53 UTC, danrabbit approved these changes
In that case, let's gooooo :rocket:

2021-11-11 18:53 UTC, merged

2021-12-09 23:59 UTC, btkostner commented
Hello, I just wanted to drop by and say that the Stripe token integration for the new AppCenter dashboard is live. You can now go to https://beta.developer.elementary.io/ and type your app URL in. There you will see a "Get a Stripe key" link to log in with Stripe. After you complete your on-boarding you will see the needed Stripe token. Let me know if you have any questions.

2021-12-10 15:22 UTC, ChildishGiant commented
I logged into an already existing stripe account and it redirected me straight back to the AppCenter dashboard once I logged in. I've gone back into the stripe dashboard but there's no new key. Under Events this is all that happened: 
![image](https://user-images.githubusercontent.com/13716824/145597991-6b5b7006-c039-472b-90a4-36d0cf4b376a.png)