com.github.philip-scott.notes-up 2.0.3
elementary/appcenter-reviews pull request #210
Opened 2021-11-23 19:50 UTC by danrabbit

Repository: [Philip-Scott/Notes-up](https://github.com/Philip-Scott/Notes-up)
Submitted By: @Philip-Scott

2021-11-24 00:35 UTC, Philip-Scott requested changes
I don't have push access to this repo, but I'm leaving the new release info as a suggestion for a hopefully easy change :)

2021-11-24 00:35 UTC, Philip-Scott commented on applications/com.github.philip-scott.notes-up.json
> +  "version": "2.0.3"
```suggestion
  "version": "2.0.4"
```

2021-11-24 00:35 UTC, Philip-Scott commented on applications/com.github.philip-scott.notes-up.json
> +  "commit": "442bd28ced08332c6f9574c948993fac232a5465",
```suggestion
  "commit": "29e72f17232a0c5c0671ce58c2b5832ca5041879",
```

2021-11-24 19:47 UTC, Philip-Scott commented
Should this file be renamed to `com.github.philip_scott.notes-up.json` after the next Notes-Up release? Flatpak does not allow for a `-` before the last section of the RDNN

2021-11-24 19:57 UTC, danrabbit commented
@Philip-Scott yeah your ID will need to be consistent throughout, so I'd suggest switching everything over to use the underscore

2021-11-25 01:20 UTC, Philip-Scott commented on applications/com.github.philip_scott.notes-up.json
> +  "version": "2.0.4"
```suggestion
  "version": "2.0.5"
```

2021-11-25 01:21 UTC, Philip-Scott reviewed
New release should have the new RDNN

2021-11-25 01:21 UTC, Philip-Scott commented on applications/com.github.philip_scott.notes-up.json
> +  "version": "2.0.4"
```suggestion
  "version": "2.0.5"
```

2021-11-25 01:21 UTC, Philip-Scott commented on applications/com.github.philip_scott.notes-up.json
> +  "commit": "29e72f17232a0c5c0671ce58c2b5832ca5041879",
```suggestion
  "commit": "47d311735e1b59e11e20e02b12a7b9aa01ccf89c",
```

2021-11-25 04:20 UTC, danrabbit commented
@Philip-Scott everything works now, but you have non-default window controls :upside_down_face:

2021-11-30 04:37 UTC, Philip-Scott reviewed
Fixed screenshots on the latest release :)

2021-11-30 04:37 UTC, Philip-Scott commented on applications/com.github.philip_scott.notes-up.json
> +  "commit": "47d311735e1b59e11e20e02b12a7b9aa01ccf89c",
```suggestion
  "commit": "7c7e26a8e67a49a92885f304fc5fa8ccb4be1d05",
```

2021-11-30 04:37 UTC, Philip-Scott commented on applications/com.github.philip_scott.notes-up.json
> +  "version": "2.0.5"
```suggestion
  "version": "2.0.6"
```

2021-12-01 19:18 UTC, danrabbit commented
Let's goooo :rocket:

2021-12-01 19:18 UTC, merged