com.github.lafydev.animage 1.0.9
elementary/appcenter-reviews pull request #47
Opened 2021-08-04 16:33 UTC by danrabbit

- Repository: [Lafydev/Animage](https://github.com/Lafydev/Animage)
 - Submitted By: @Lafydev

2021-08-04 17:29 UTC, danrabbit commented
:x: https://github.com/Lafydev/Animage/issues/11
:x: https://github.com/Lafydev/Animage/issues/12

2021-08-12 17:02 UTC, cassidyjames commented
@Lafydev 

- [ ] It looks like your screenshot is still on elementary OS 5, not OS 6; screenshots for the OS 6 release should be taken on OS 6.
- [ ] Your app might be missing Flatpak configuration for access to files; I can't seem to see or open any files with the Open button

2021-08-20 03:08 UTC, cassidyjames requested changes
Above issues need to be addressed before re-reviewing.

2021-08-20 18:24 UTC, cassidyjames approved these changes

2021-08-20 18:25 UTC, merged