Create io.github.ellie_commons.tomato
elementary/appcenter-reviews pull request #544
Opened 2024-12-26 17:42 UTC by alainm23

## Review Checklist

- [ ] App opens
- [ ] Does what it says
- [ ] Categories match

### AppData
- [ ] Name is unique and non-confusing
- [ ] Matches description
- [ ] Matches screenshot
- [ ] Launchable tag with matching ID
- [ ] Release tag with matching version and YYYY-MM-DD date
- [ ] Custom colors meet WCAG A contrast or greater
- [ ] OARS info matches

### Flatpak
- [ ] Uses elementary runtime
- [ ] Sandbox permissions are reasonable

![image](https://github.com/user-attachments/assets/3d36853b-0862-4e5a-bc65-b683fd9b9ba1)

2025-01-21 14:01 UTC, alainm23 commented
@elementary/app-reviewers

2025-01-22 14:15 UTC, ryonakano requested changes
I'm sorry for late review :bow:

I created the following issues as requested changes:

- https://github.com/ellie-commons/tomato/issues/2
- https://github.com/ellie-commons/tomato/issues/3
- https://github.com/ellie-commons/tomato/issues/4

I'd like you to address them.

2025-01-22 14:28 UTC, ryonakano commented
Another thing I'm concerned is the app name: Tomato.

I think your app is fork/continuation of https://github.com/tomatoers/tomato, which was anciently available at AppCenter (maybe in 0.4 Loki). And you inherited the app name, which is potentially a problem if the original author changed their mind, come back to develop the app, and tried publishing the app on AppCenter again. While this wouldn't happen because the original repository has been archived, it's technically possible to unarchive their repository.
So I'm not sure if this is fine or not good.

@danirabbit Should we choose a different name for a forked app from the original app which is previously available on AppCenter?

2025-01-22 16:00 UTC, danirabbit commented
I think since it's archived and the original author hasn't tried to publish in all these years that's probably okay

2025-01-24 15:53 UTC, ryonakano approved these changes
LGTM.

@elementary/app-reviewers I'm new to review app submissions. Feel free to review if I'm missing something.

2025-01-24 17:33 UTC, merged